DTOpenDist$Status <- "Open"
DTAnalysisDist$Status <- "Analysis"
DTBacklogDist$Status <- "Backlog"
DTIPDist$Status <- "In_Progress"
DTResolvedDist$Status <- "Resolved"
DTReleasingDist$Status <- "Releasing"
DTClosedDist$Status <- "Closed"
DTDoneDist$Status <- "Done"
